cabal-version: 3.0
name: devastator
version: 0.1.0.0
license: BSD-3-Clause
license-file: LICENSE
build-type: Simple

common ghc-options-stanza
  ghc-options:
    -Wall
    -Wno-unused-imports
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints

library
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: src
  exposed-modules:
    Devastator.Cert
    Devastator.Fiber
    Devastator.Filter
    Devastator.Framing
    Devastator.Ledger
    Devastator.Null.Dyadic
    Devastator.Null.ShortWave
    Devastator.Replay
    Devastator.Run
    Devastator.Spectral
    Devastator.Tape
    Devastator.Toy
    Devastator.Verdict

  build-depends:
    base >=4.18 && <5,
    circuits-agent,
    circuits-parser >=0.1 && <0.2,
    containers >=0.6 && <0.9,
    scientific >=0.3 && <0.4,
    text >=2.0 && <3,
    time,
    vector >=0.13 && <0.14,

executable devastator-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: app
  main-is: toy-axioma.hs
  build-depends:
    base,
    circuits-agent,
    devastator,
    text,

executable devastator-replay-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: app
  main-is: replay-axioma.hs
  build-depends:
    base,
    circuits-agent,
    devastator,
    text,

executable devastator-ledger-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: app
  main-is: ledger-axioma.hs
  build-depends:
    base,
    circuits-agent,
    devastator,
    directory,
    filepath,
    text,

executable devastator-fiber-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: app
  main-is: fiber-axioma.hs
  build-depends:
    base,
    circuits-agent,
    containers,
    devastator,
    text,

executable devastator-filter-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: app
  main-is: filter-axioma.hs
  build-depends:
    base,
    circuits-agent,
    containers,
    devastator,
    directory,
    filepath,
    text,

executable devastator-shortwave-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: app
  main-is: shortwave-axioma.hs
  build-depends:
    base,
    devastator,

executable devastator-null-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: app
  main-is: null-axioma.hs
  build-depends:
    base,
    circuits-agent,
    devastator,
    text,
